// modulo03-react/clarim-diario-news/clarim-diario/src/components/NewsCard/NewsCard.jsx
import "./NewsCard.css";

function NewsCard({ categoria, titulo, resumo }) {
  return (
    <article className="card">
      <span className="card__categoria">{categoria}</span>
      <h3 className="card__titulo">{titulo}</h3>

      {resumo && <p className="card__resumo">{resumo}</p>}
    </article>
  );
}

export default NewsCard;

// desenvolvimento_web/aula23-prs_webcomponents/js/components/news-card.js
class NewsCard extends HTMLElement {
    connectedCallback() {
        const categoria = this.getAttribute('categoria') || '';
        const titulo = this.getAttribute('titulo') || '';
        const resumo = this.getAttribute('resumo') || '';

        this.innerHTML = `
            <article class="cartao">
                <span class="categoria">${categoria}</span>
                <h3 class="cartao__titulo">${titulo}</h3>
                ${resumo ? `<p class="cartao__resumo">${resumo}</p>` : ''}
            </article>
        `;
    }
}
customElements.define('news-card', NewsCard);
